-- Safa Rosy demo catalog — idempotent seed
INSERT INTO products (id, name, category, subcategory, description, price, old_price, image, tags, rating, reviews, badge) VALUES
('glow-vit-c-serum', 'Glow Vitamin C Serum 15%', 'skin', 'serum', 'Brightening antioxidant serum that fades dark spots and revives dull, tired skin.', 620, 780, 'https://images.pexels.com/photos/15930069/pexels-photo-15930069.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","serum","dullness","pigmentation","brightening","glow"]'::jsonb, 4.8, 214, 'Best Seller'),
('hyaluron-quench-serum', 'Hyaluronic Quench Serum', 'skin', 'serum', 'Triple-weight hyaluronic acid that drenches skin in weightless hydration.', 540, NULL, 'https://images.pexels.com/photos/15930068/pexels-photo-15930068.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","serum","dry","dehydration","hydration"]'::jsonb, 4.7, 186, NULL),
('niacinamide-pore-serum', 'Niacinamide 10% + Zinc', 'skin', 'serum', 'Oil-balancing serum that tightens the look of pores and calms breakouts.', 460, 560, 'https://images.pexels.com/photos/35101526/pexels-photo-35101526.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","serum","oily","acne","pores"]'::jsonb, 4.6, 305, 'On Offer'),
('salicylic-clarifying-cleanser', 'Salicylic Clarifying Cleanser', 'skin', 'cleanser', 'Gentle daily gel cleanser with 2% BHA to keep pores clear without stripping.', 380, NULL, 'https://images.pexels.com/photos/13573722/pexels-photo-13573722.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","cleanser","oily","acne","pores"]'::jsonb, 4.5, 142, NULL),
('ceramide-barrier-cream', 'Ceramide Barrier Cream', 'skin', 'moisturizer', 'Rich ceramide cream that repairs the barrier and comforts dry, sensitive skin.', 690, 820, 'https://images.pexels.com/photos/24602069/pexels-photo-24602069.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","moisturizer","dry","sensitive","redness","barrier"]'::jsonb, 4.9, 168, 'Best Seller'),
('retinol-renew-night-cream', 'Retinol Renew Night Cream', 'skin', 'night cream', 'Encapsulated retinol that smooths fine lines and firms skin while you sleep.', 850, NULL, 'https://images.pexels.com/photos/10825668/pexels-photo-10825668.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","cream","aging","wrinkles"]'::jsonb, 4.6, 97, NULL),
('calendula-calm-toner', 'Calendula Calm Toner', 'skin', 'toner', 'Alcohol-free toner that soothes redness and rebalances sensitive skin.', 340, NULL, 'https://images.pexels.com/photos/8101534/pexels-photo-8101534.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","toner","sensitive","redness","normal"]'::jsonb, 4.4, 88, NULL),
('invisible-spf50', 'Invisible Shield SPF 50', 'skin', 'sunscreen', 'Weightless, no-white-cast sunscreen — daily protection against dark spots.', 520, 640, 'https://images.pexels.com/photos/20384794/pexels-photo-20384794.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["skin","sunscreen","protection","pigmentation","daily"]'::jsonb, 4.7, 251, 'On Offer'),
('argan-repair-mask', 'Argan Deep Repair Mask', 'hair', 'hair mask', 'Ten-minute argan and keratin mask that rebuilds dry, damaged lengths.', 580, NULL, 'https://images.pexels.com/photos/9909784/pexels-photo-9909784.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","mask","dry","damage","wavy","curly","repair"]'::jsonb, 4.8, 176, 'Best Seller'),
('keratin-smooth-shampoo', 'Keratin Smooth Shampoo', 'hair', 'shampoo', 'Sulfate-free smoothing shampoo that tames frizz for straight and wavy hair.', 420, NULL, 'https://images.pexels.com/photos/10427812/pexels-photo-10427812.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","shampoo","frizz","straight","wavy","smooth"]'::jsonb, 4.5, 139, NULL),
('biotin-scalp-tonic', 'Biotin Anti-Fall Tonic', 'hair', 'scalp tonic', 'Lightweight caffeine and biotin scalp tonic that targets hair fall at the root.', 750, 890, 'https://images.pexels.com/photos/10110225/pexels-photo-10110225.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","tonic","hairfall","thinning","scalp"]'::jsonb, 4.6, 203, 'On Offer'),
('curl-define-cream', 'Curl Define Cream', 'hair', 'styling cream', 'Shea-based defining cream for bouncy, frizz-free curls and coils.', 390, NULL, 'https://images.pexels.com/photos/6429662/pexels-photo-6429662.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","styling","curly","coily","frizz","define"]'::jsonb, 4.7, 164, NULL),
('tea-tree-scalp-shampoo', 'Tea Tree Scalp Shampoo', 'hair', 'shampoo', 'Purifying tea tree formula that clears dandruff and refreshes the scalp.', 440, NULL, 'https://images.pexels.com/photos/10427810/pexels-photo-10427810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","shampoo","dandruff","scalp"]'::jsonb, 4.4, 121, NULL),
('color-guard-purple-shampoo', 'Color Guard Purple Shampoo', 'hair', 'shampoo', 'Violet pigments that neutralize brassiness in blonde and colored hair.', 480, NULL, 'https://images.pexels.com/photos/10427813/pexels-photo-10427813.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["hair","shampoo","colored","blonde","dyed","toning"]'::jsonb, 4.5, 98, NULL),
('shea-intensive-body-butter', 'Shea Intensive Body Butter', 'body', 'body butter', 'Whipped shea butter that melts into very dry skin for 48-hour comfort.', 360, 450, 'https://images.pexels.com/photos/9774854/pexels-photo-9774854.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["body","butter","verydry","dry","rough"]'::jsonb, 4.8, 232, 'On Offer'),
('aha-smoothing-body-lotion', 'AHA Smoothing Body Lotion', 'body', 'body lotion', 'Lactic-acid lotion that smooths bumps and brightens uneven tone.', 470, NULL, 'https://images.pexels.com/photos/7691166/pexels-photo-7691166.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["body","lotion","exfoliation","brightening","smoothing","keratosis"]'::jsonb, 4.6, 84, NULL),
('sugar-glow-body-scrub', 'Sugar Glow Body Scrub', 'body', 'body scrub', 'Fine sugar crystals with vitamin C for polished, radiant-looking skin.', 320, NULL, 'https://images.pexels.com/photos/9774603/pexels-photo-9774603.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["body","scrub","exfoliation","brightening","glow"]'::jsonb, 4.5, 145, NULL),
('caffeine-firming-body-cream', 'Caffeine Firming Cream', 'body', 'body cream', 'Fast-absorbing caffeine cream that visibly tightens and energizes skin.', 560, NULL, 'https://images.pexels.com/photos/9774608/pexels-photo-9774608.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["body","cream","firming","cellulite"]'::jsonb, 4.3, 76, NULL),
('rosy-veil-body-mist', 'Rosy Veil Body Mist', 'body', 'body mist', 'A soft rose-and-musk veil that keeps you fresh all day.', 290, NULL, 'https://images.pexels.com/photos/6690232/pexels-photo-6690232.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940', '["body","mist","fragrance","freshness"]'::jsonb, 4.7, 189, 'Best Seller')
ON CONFLICT (id) DO NOTHING;
